name = "domain-check"
main = "src/index.js"
compatibility_date = "2025-11-17"
keep_vars = true

# KV 命名空间绑定 (必须)
[[kv_namespaces]]
binding = "domain-check" 
id = "f1cfbb300e1a434798247e69393b78a7" # 替换成你实际的 KV ID

# Cron Triggers 定时任务
[triggers]
crons = ["0 1,13 * * *"] # 北京时间 9:00 和 21:00
